// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI9QhBRG1Jn3f0nr9XozkNs3a2ZLtN2zE',
    appId: '1:289244336949:web:4459e4c7906b600439b27c',
    messagingSenderId: '289244336949',
    projectId: 'jchat-messaging-app',
    authDomain: 'jchat-messaging-app.firebaseapp.com',
    storageBucket: 'jchat-messaging-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV09pvhXDlor_wGU2IXc_2r5OSEQL8fc8',
    appId: '1:289244336949:android:4ae0291e967c447c39b27c',
    messagingSenderId: '289244336949',
    projectId: 'jchat-messaging-app',
    storageBucket: 'jchat-messaging-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvOHFm6vjMoo9vqPFi1d2MJpFl97Oxxwk',
    appId: '1:289244336949:ios:51de0ccee0bb976439b27c',
    messagingSenderId: '289244336949',
    projectId: 'jchat-messaging-app',
    storageBucket: 'jchat-messaging-app.appspot.com',
    iosBundleId: 'com.example.jchatapp',
  );
}
